import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeRegistry from './ThemeRegistry';
import CssBaseline from '@mui/material/CssBaseline';
import { Container } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <ThemeRegistry options={{ key: 'mui' }}>
          <Container maxWidth="md">{children}</Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
